config/routes.rb
Rails.application.routes.draw do
	get '/games/add_players', to: 'game#add_players', as: 'add_players'
	post '/games/collect_card', to: 'game#collect_card', as: 'collect_card'
	post '/games/end_turn', to: 'game#end_turn', as: 'end_turn'
    resources :game, path: 'games' do
	  	post '/create_team', to: 'game#create_team', as: 'create_team'
	  	post '/create_player', to: 'game#create_player', as: 'create_player'
	end
  root 'title#index'

  get 'game/new'

  get 'level/show'

  get 'level/next'

  get 'characters/index'

  get 'characters/select'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
	has_many :teams

	def calculate_game_state
		self.teams.each do |team|
			if team.cards.where(level: "three").count >= 2 then
				team.update_attributes(level: "win")
				self.update_attributes(status: "#{team.name} won")
			elsif team.cards.where(level: "two").count >= 2 then
				team.update_attributes(level: "three")
			elsif team.cards.where(level: "one").count >= 3 then
				team.update_attributes(level: "two")
			end
		end
	end

	def current_player
		if self.current_player_id == nil then

			self.update_attributes({current_player_id:self.teams.map {|x| x.players}.flatten.first.id})
		end
		Player.find(self.current_player_id)
	end

	def current_team
		Team.find(current_player.team_id)
	end

	
	def update_current_player
		all_players = all_player_ids
		current_index = current_player_index
		before_self = all_players[0..(current_index)]
		after_self = all_players[(current_index+1)..-1]
		circular_array = [current_player.id, *after_self, *before_self]
		self.update_attributes({current_player_id: circular_array[1]})
		return Player.find(self.current_player_id)
	end

	private
	def current_player_index
		self.teams.map {|x| x.players.map {|y| y.name} }.flatten.find_index Player.find(self.current_player_id).name
	end
	def all_player_ids
		self.teams.map {|x| x.players.map {|y| y.id} }.flatten
	end
end

app/models/player.rb
class Player < ApplicationRecord
	def pickup_card
		team = Team.find(self.team_id)
		possible_cards = Card.where(level: team.level)
		random_no = Random.rand(possible_cards.count - 1)
		return possible_cards[random_no]
	end
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :players
	has_many :cards

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
  end

  def select
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  	@games = Game.all
  	@no_games = Game.all.count == 0
  end

  def new
  	@game = Game.new
  end

  def create
  	Game.create(game_params)
  	redirect_to game_path(Game.last)
  end

  def show
  	@game = Game.find(params[:id])
  	@game.calculate_game_state
  end

  def select_teams
  	@game = Game.find(params[:game_id])
  end

  def create_team
  	@game = Game.find(params[:game_id])
  	if @game.teams.count < 2 then #validation
  		@team = Team.find(params[:team_id]).dup
  		@team.save
  		@game.teams << @team
  		redirect_to add_players_path(team_id: @team.id)
  	end
  end

  def add_players
  	@team = Team.find(params[:team_id])
  end

  def create_player
  	@team = Team.find(params[:team_id])
  	if @team.players.count < 5 then #validation
  		@player = Player.find(params[:player_id]).dup
  		@player.save
  		@team.players << @player
  		redirect_to add_players_path(team_id: @team.id)
  	end
  end

  def collect_card
  	card = Card.find(params[:card]).dup
  	card.save
  	cur_player = Player.find(params[:current_player])
  	Team.find(cur_player.team_id).cards << card
  	game = Game.find(Team.find(cur_player.team_id).game_id)
  	game.update_current_player
  	redirect_to game_path(game)
  end

  def end_turn
  	Game.find(params[:game]).update_current_player
  	redirect_to game_path(params[:game])
  end

  def game_params
    params.require(:game).permit(:name, :status)
  end

  def team_params
  	params.require(:team).permit(:name)
  end
end

app/controllers/level_controller.rb
class LevelController < ApplicationController
  def show
  end

  def next
  end
end

app/controllers/title_controller.rb
class TitleController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/game_helper.rb
module GameHelper
	def drinks_level(level)
		if(level == "three")
			return "Spirits (40% +)"
		elsif(level == "two")
			return "Beer"
		elsif(level == "one")
			return "Wine"
		end
	end
	def drinks_image(level)
		if(level == "three")
			return "http://www.gosupermarkets.com/media/catalog/category/Alcohol-44_498x416_.jpg"
		elsif(level == "two")
			return "http://www.edgewoodyachtclub.com/wp-content/uploads/2016/01/beer.gif"
		elsif(level == "one")
			return "http://theozsafari.com.au/wp-content/uploads/2015/04/wine-glasses.jpg"
		end
	end
end

app/helpers/level_helper.rb
module LevelHelper
end

app/helpers/title_helper.rb
module TitleHelper
end

app/views/characters/index.html.erb
<h1>Characters#index</h1>
<p>Find me in app/views/characters/index.html.erb</p>

app/views/characters/select.html.erb
<h1>Characters#select</h1>
<p>Find me in app/views/characters/select.html.erb</p>

app/views/game/add_players.html.erb
<div class="ui container" style="margin-top:25px">
	<h2><%= @team.name %><h1>

	<h3>Add players:</h3>
	<div class="ui six column centered grid">
	<% Player.where(team_id: nil, team_name: @team.name).each do |player| %>
		<% unless @team.players.map {|x| x.name}.include? player.name %>
		<div class="column">
			<a class="ui fluid link card" 
				href="<%= game_create_player_path({team_id: @team.id, player_id: player.id, game_id: @team.game_id}) %>" data-method="post">
				<div class="image">
			      <img src="<%= image_path(player.image_url) %>">
			    </div>
			</a>
			<h3><%= player.name %></h3>
		</div>
		<% end %>
	<% end %>
	</div>
	<% if @team.players.count > 0 then %>
		<h3>Current Players:</h3>
		<div class="ui six column centered grid">
		<% @team.players.each do |player| %>
			<div class="column">
				<div class="ui fluid link card">
					<div class="image">
				      <img src="<%= image_path(player.image_url) %>">
				    </div>
				</div>
				<h3><%= player.name %></h3>
			</div>
		<% end %>
		</div>
		<a style="margin-top:50px" class="ui inverted fluid button" href="<%= game_path(Game.find(@team.game_id)) %>">Done</a>
	<% end %>
	</div>
</div>

app/views/game/index.html.erb
<div class="ui text container">
	<h2 style="font-family: 'textileregular'; text-align:center; margin-top:50px">New / Load Game </h2>
	<table class="ui inverted table">
		<% if @no_games then %>
			<p style="text-align:center">
			You haven't played any previous games... Play a <a href="<%= new_game_path %>">new one</a>?
			</p>
		<% else %>
		  <thead>
		    <tr>
		      <th>Game name</th>
		      <th>Status</th>
		      <th>Last played</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<% @games.each do |game| %>
		    <tr>
		      <td><a href="<%= game_path(game) %>"><%= game.name %></a></td>
		      <td><%= game.status %></td>
		      <td><%= time_ago_in_words game.updated_at %> ago</td>
		    </tr>
		    <% end %>
		  </tbody>
		  <a href="<%= new_game_path %>" class="ui right aligned inverted button">New game</a>
		<% end %>
	</table>
</div>

app/views/game/new.html.erb
<div class="ui text container">
	<h2 style="font-family: 'textileregular'; text-align:center; margin-top:50px">New Game </h2>
	<%= form_for(@game, url: game_index_path, html: { method: :post }) do |f| %>
	<div class="ui  inverted segment form">
		<div class="ui field">
			<label>Game name</label>
			<%= f.text_field :name %>
		</div>
		<%= f.hidden_field :status, value: "Ongoing" %>
		<div style="text-align:right">
			
			<a href="<%= game_index_path %>" class="ui secondary inverted button">Cancel</a>
			<%= f.submit "Create and play game", class: "ui inverted button" %>
		</div>
	</div>
	<% end %>
</div>

app/views/game/show.html.erb
<% unless @game.teams.map {|x| x.level}.include? "win" %>
<div class="ui container" style="margin-top:25px">
	<div class="ui inverted segment">
		<div class="ui two column grid">
			<% @game.teams.each  do |team| %>
				<div class="column">
					<h4>Team <%= team.name %></h4>
					<h5>Level: <%= team.level %></h5>
					<img style="margin:auto; text-align:center" class="ui small image" src="<%= drinks_image(team.level) %>"/>
				</div>
			<% end %>
		</div>
	</div>
	
	<% if @game.teams.count < 2 %>
		<h2>Select your team!</h2>
		<div class="ui three column centered grid">
		<% Team.where(game_id: nil).each do |team| %>
			<% unless @game.teams.map {|x| x.name}.include? team.name %>
			<div class="column">
				
				<a class="ui fluid link card" 
					href="<%= game_create_team_path({team_id: team.id, game_id: @game.id}) %>" data-method="post">
					<div class="image">
				      <img src="<%= image_path(team.image_url) %>">
				    </div>
				</a>
				<h3><%= team.name %></h3>
			</div>
			<% end %>
		<% end %>
		</div>
	<% else %>
		<!-- Game starts! -->
		<% @card = @game.current_player.pickup_card %>
		<h2>Current player is: <%= @game.current_player.name %>, of team <%= @game.current_team.name %></h2>
		<div style="text-align:center; margin:auto;">
			<div class="ui shape">
			  <div class="sides">
			    <div class="active side">
					<div class="ui card">
					    <div class="content">
							<div class="header"><%= @card.card_type %></div>
							<div class="description">
								<%= @card.front %>
							</div>

					    </div>
					    <% if @card.back %>
							<div class="ui bottom attached button flip-button">
						      Flip over
						    </div>
						    <% end %>
					</div>
				</div>
				<div class="side">
					<div class="ui card">
					    <div class="content">
							<div class="header"><%= @card.card_type %>: Answer</div>
							<div class="description">
								<%= @card.back %>
							</div>
					    </div>
					</div>
				</div>
			</div>
			</div>

		</div>
		<div style="text-align:center; margin-top:25px">
		<% if @card.card_type == "Trivia" %>
			<div style="text-align:center; margin-top:25px">
				<div class="trivia-actions">
					<a href="<%= collect_card_path({card: @card, current_player: @game.current_player}) %>" class="ui green button" data-method="post">Correct</a>
					<a class="ui red button" href="<%= end_turn_path({game: @game}) %>" data-method="post">Incorrect</a>
				</div>
			</div>
		<% elsif @card.front.gsub(/All Play/).count > 0 %>
			<div style="text-align:center; margin-top:25px">
			<% @game.teams.each do |team| %>
				<a href="<%= collect_card_path({card: @card, current_player: team.players.first}) %>"
				   class="ui button"
				   data-method="post"><%= team.name %></a>
			<% end %>
			</div>
		<% elsif @card.front.match(/\w minutes/)  %>
			<% minutes = @card.front.match(/\w minutes/)[0].match(/\w/)[0] %>
			This is a timed one!
			<span id="time">0<%= minutes %>:00</span> remaining!
			<script>
			function startTimer(duration, display) {
			    var timer = duration, minutes, seconds;
			    setInterval(function () {
			        minutes = parseInt(timer / 60, 10);
			        seconds = parseInt(timer % 60, 10);

			        minutes = minutes < 10 ? "0" + minutes : minutes;
			        seconds = seconds < 10 ? "0" + seconds : seconds;

			        display.text(minutes + ":" + seconds);
			        if( (minutes + ":" + seconds) == "0:00") {
			        	console.log("IM SO DONE")
			        	break;
			        }
			        if (--timer < 0) {
			            timer = duration;
			        }
			    }, 1000);
			}

			jQuery(function ($) {
			        display = $('#time');
			    startTimer(60 * <%= minutes %>, display);
			});
			</script>
		<% else %>
			<div style="text-align:center; margin-top:25px">
				<div>
					<a href="<%= collect_card_path({card: @card, current_player: @game.current_player}) %>" class="ui green button" data-method="post">Correct</a>
					<a class="ui red button" href="<%= end_turn_path({game: @game}) %>" data-method="post">Incorrect</a>
				</div>
			</div>
		<% end %>
		</div>
		
	<% end %>
</div>
<script>
$(document).ready( () => {
$(".flip-button").on("click", () => {
	$('.shape').shape('flip over');
	$('.trivia-actions').css("display", "inline-block")
})
})
</script>
<style>
 .trivia-actions {
 	margin:auto !important;
 	text-align:center !important;
 	white-space: nowrap;
 	display:none;
 }
</style>
<% else %>
	<h1>Team <%= @game.teams.select {|x| x.level == "win"}.first.name %> Wins!</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChardeeMacdennis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.css">
  	<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.js"></script>
  </head>

  <body>
  	<% unless current_page?(controller: 'title', action: 'index') then %>
  	<div class="ui container" style="margin-top:25px">
		<h1 style="font-family: 'textileregular'; text-align:center; margin-top:50px"><a href="/">CharDee MacDennis</a></h1>
	</div>
	<% end %>
    <%= yield %>

  </body>
  
</html>

app/views/level/next.html.erb
<h1>Level#next</h1>
<p>Find me in app/views/level/next.html.erb</p>

app/views/level/show.html.erb
<h1>Level#show</h1>
<p>Find me in app/views/level/show.html.erb</p>

app/views/title/index.html.erb
<div id="centerid" class="center Absolute-Center" style="height:200px">
    CharDee MacDennis 3:<br>
    TechPocalypse Edition
</div>
<div class="bWrapper Absolute-Center" style="height:200px; margin-top:70vh">
    <a href="<%= game_index_path %>" class="ui inverted button">Play</a>
</div>
<div style="visibility: hidden; height: 0; overflow: hidden;">
    <iframe width="420" height="315" src="https://www.youtube.com/embed/WKFIDLMliHo?autoplay=1" frameborder="0" allowfullscreen></iframe>
</div>